import type { ChartTypeMeta } from './chart';

export const CHART_CATALOGUE: ChartTypeMeta[] = [
  // ── Line ──────────────────────────────────────────
  {
    id: 'line',
    name: 'Single line',
    description: 'One metric tracked over time. GDP, temperature, stock price.',
    category: 'line',
    engine: 'chartjs',
    dataShape: 'single-series',
    icon: '📈',
  },
  {
    id: 'multi-line',
    name: 'Multi-line comparison',
    description: '2–5 series on the same axis. Countries, regions, categories.',
    category: 'line',
    engine: 'chartjs',
    dataShape: 'multi-series',
    icon: '📉',
  },
  {
    id: 'area',
    name: 'Area chart',
    description: 'Line with shaded fill below. Emphasises volume or accumulation.',
    category: 'line',
    engine: 'chartjs',
    dataShape: 'single-series',
    icon: '🏔',
  },
  {
    id: 'stacked-area',
    name: 'Stacked area',
    description: 'Multiple filled areas stacked. Shows composition over time.',
    category: 'line',
    engine: 'chartjs',
    dataShape: 'multi-series',
    icon: '🗻',
  },

  // ── Bar ───────────────────────────────────────────
  {
    id: 'bar',
    name: 'Vertical bar',
    description: 'Category vs. value. Works best with ≤8 categories.',
    category: 'bar',
    engine: 'chartjs',
    dataShape: 'single-series',
    icon: '📊',
  },
  {
    id: 'grouped-bar',
    name: 'Grouped bars',
    description: 'Two series side-by-side per category. Before vs. after, A vs. B.',
    category: 'bar',
    engine: 'chartjs',
    dataShape: 'multi-series',
    icon: '📊',
  },
  {
    id: 'stacked-bar',
    name: 'Stacked bar',
    description: 'Part-to-whole within each category. Good for 2–4 components.',
    category: 'bar',
    engine: 'chartjs',
    dataShape: 'multi-series',
    icon: '📊',
  },
  {
    id: 'histogram',
    name: 'Histogram',
    description: 'Frequency distribution of continuous data. Bin widths matter.',
    category: 'distribution',
    engine: 'chartjs',
    dataShape: 'distribution',
    icon: '📊',
  },
  {
    id: 'waterfall',
    name: 'Waterfall chart',
    description: 'Running total with increases and decreases. P&L breakdowns.',
    category: 'bar',
    engine: 'svg',
    dataShape: 'waterfall',
    icon: '🪜',
  },

  // ── Scatter ───────────────────────────────────────
  {
    id: 'scatter',
    name: 'Scatter plot',
    description: 'Two variables, correlation visible. Outliers auto-labelled.',
    category: 'scatter',
    engine: 'chartjs',
    dataShape: 'xy',
    icon: '⚬',
  },
  {
    id: 'bubble',
    name: 'Bubble chart',
    description: 'Three variables: x, y, and size. Population, GDP, emissions.',
    category: 'scatter',
    engine: 'chartjs',
    dataShape: 'xyz',
    icon: '🫧',
  },

  // ── Part-to-whole ─────────────────────────────────
  {
    id: 'pie',
    name: 'Pie chart',
    description: 'Proportional slices of a whole. Best with ≤6 categories.',
    category: 'part-to-whole',
    engine: 'chartjs',
    dataShape: 'key-value',
    icon: '🥧',
  },
  {
    id: 'donut',
    name: 'Donut chart',
    description: 'Pie with centre cut out. Cleaner look, room for a stat.',
    category: 'part-to-whole',
    engine: 'chartjs',
    dataShape: 'key-value',
    icon: '🍩',
  },
  {
    id: 'treemap',
    name: 'Treemap',
    description: 'Nested rectangles sized by value. Budget, market cap, disk usage.',
    category: 'part-to-whole',
    engine: 'svg',
    dataShape: 'hierarchical',
    icon: '🟩',
  },

  // ── Ranking / Horizontal ──────────────────────────
  {
    id: 'lollipop',
    name: 'Lollipop chart',
    description: 'Cleaner than bars for long rankings. Dot on a stem reduces ink.',
    category: 'ranking',
    engine: 'svg',
    dataShape: 'key-value',
    icon: '🍭',
  },
  {
    id: 'diverging-bar',
    name: 'Diverging bar',
    description: 'Bars extend left and right from centre. Survey / Likert data.',
    category: 'horizontal',
    engine: 'svg',
    dataShape: 'pyramid',
    icon: '↔',
  },
  {
    id: 'population-pyramid',
    name: 'Population pyramid',
    description: 'Age-gender demographics. Two mirrored horizontal bar sets.',
    category: 'horizontal',
    engine: 'svg',
    dataShape: 'pyramid',
    icon: '🏛',
  },

  // ── Distribution ──────────────────────────────────
  {
    id: 'box-plot',
    name: 'Box & whisker',
    description: 'Min, Q1, median, Q3, max. Compare distributions across groups.',
    category: 'distribution',
    engine: 'svg',
    dataShape: 'distribution',
    icon: '📦',
  },
  {
    id: 'violin-plot',
    name: 'Violin plot',
    description: 'Distribution shape + density. Richer than box plots.',
    category: 'distribution',
    engine: 'svg',
    dataShape: 'distribution',
    icon: '🎻',
  },

  // ── Other ─────────────────────────────────────────
  {
    id: 'radar',
    name: 'Radar / spider',
    description: 'Compare multivariate data on radial axes. Skill profiles, ratings.',
    category: 'other',
    engine: 'chartjs',
    dataShape: 'multi-series',
    icon: '🕸',
  },
  {
    id: 'heatmap',
    name: 'Heatmap',
    description: 'Colour intensity in a grid. Correlations, schedules, matrices.',
    category: 'other',
    engine: 'svg',
    dataShape: 'matrix',
    icon: '🟥',
  },
  {
    id: 'bullet-graph',
    name: 'Bullet graph',
    description: 'Actual vs. target with qualitative bands. KPI dashboards.',
    category: 'other',
    engine: 'svg',
    dataShape: 'bullet',
    icon: '🎯',
  },
  {
    id: 'dot-matrix',
    name: 'Dot matrix',
    description: 'Grid of dots coloured by category. "X out of 100" visualisations.',
    category: 'other',
    engine: 'svg',
    dataShape: 'key-value',
    icon: '⚫',
  },
  {
    id: 'span-chart',
    name: 'Span / range chart',
    description: 'Shows min–max range per category. Temperature, salary bands.',
    category: 'other',
    engine: 'svg',
    dataShape: 'range',
    icon: '↕',
  },
  {
    id: 'radial-bar',
    name: 'Radial bar',
    description: 'Bars wrapped around a circle. Progress rings, category compare.',
    category: 'other',
    engine: 'svg',
    dataShape: 'key-value',
    icon: '🔘',
  },
  {
    id: 'nightingale-rose',
    name: 'Nightingale rose',
    description: 'Polar area chart — wedges sized by value. Seasonal / cyclical data.',
    category: 'other',
    engine: 'svg',
    dataShape: 'key-value',
    icon: '🌹',
  },
  {
    id: 'proportional-area',
    name: 'Proportional area',
    description: 'Circles sized by value. Simple magnitude comparison.',
    category: 'other',
    engine: 'svg',
    dataShape: 'key-value',
    icon: '⭕',
  },
  {
    id: 'pictogram',
    name: 'Pictogram',
    description: 'Icons repeated to show quantities. Accessible and editorial.',
    category: 'other',
    engine: 'svg',
    dataShape: 'key-value',
    icon: '👤',
  },
  {
    id: 'word-cloud',
    name: 'Word cloud',
    description: 'Word size proportional to frequency. Survey responses, text analysis.',
    category: 'other',
    engine: 'svg',
    dataShape: 'weighted-text',
    icon: '☁',
  },

  // ── Tier 2 — Flow & Hierarchy ─────────────────────
  {
    id: 'sankey',
    name: 'Sankey diagram',
    description: 'Flow between nodes with proportional ribbons. Energy, budgets, conversions.',
    category: 'flow',
    engine: 'svg',
    dataShape: 'flow',
    icon: '🔀',
  },
  {
    id: 'chord',
    name: 'Chord diagram',
    description: 'Circular relationships between entities. Trade flows, migrations.',
    category: 'flow',
    engine: 'svg',
    dataShape: 'matrix',
    icon: '🎵',
  },
  {
    id: 'sunburst',
    name: 'Sunburst',
    description: 'Concentric rings showing hierarchy. Drill-down from centre outward.',
    category: 'part-to-whole',
    engine: 'svg',
    dataShape: 'hierarchical',
    icon: '☀',
  },
  {
    id: 'circle-packing',
    name: 'Circle packing',
    description: 'Nested circles sized by value. Hierarchies without rectangles.',
    category: 'part-to-whole',
    engine: 'svg',
    dataShape: 'hierarchical',
    icon: '🔵',
  },
  {
    id: 'tree-diagram',
    name: 'Tree diagram',
    description: 'Hierarchical tree with branches. Org charts, taxonomies.',
    category: 'flow',
    engine: 'svg',
    dataShape: 'hierarchical',
    icon: '🌳',
  },

  // ── Tier 2 — Network & Multi-axis ────────────────
  {
    id: 'network-diagram',
    name: 'Network diagram',
    description: 'Nodes and edges showing connections. Social networks, dependencies.',
    category: 'flow',
    engine: 'svg',
    dataShape: 'network',
    icon: '🕸',
  },
  {
    id: 'parallel-coordinates',
    name: 'Parallel coordinates',
    description: 'Multi-axis comparison. Each line crosses all variable axes.',
    category: 'other',
    engine: 'svg',
    dataShape: 'matrix',
    icon: '📏',
  },
  {
    id: 'stream-graph',
    name: 'Stream graph',
    description: 'Flowing stacked areas centred on baseline. Music, topics over time.',
    category: 'line',
    engine: 'svg',
    dataShape: 'multi-series',
    icon: '🌊',
  },
  {
    id: 'arc-diagram',
    name: 'Arc diagram',
    description: 'Nodes in a line, arcs above show connections. Clean network view.',
    category: 'flow',
    engine: 'svg',
    dataShape: 'network',
    icon: '🌈',
  },
  {
    id: 'marimekko',
    name: 'Marimekko chart',
    description: 'Variable-width stacked bars. Market share by segment and size.',
    category: 'bar',
    engine: 'svg',
    dataShape: 'multi-series',
    icon: '🧱',
  },

  // ── Tier 2 — Stats & Timeline ─────────────────────
  {
    id: 'venn-diagram',
    name: 'Venn diagram',
    description: 'Overlapping circles showing set relationships. 2–3 sets.',
    category: 'other',
    engine: 'svg',
    dataShape: 'venn',
    icon: '⭕',
  },
  {
    id: 'density-plot',
    name: 'Density plot',
    description: 'Smooth probability distribution curve. Richer than histograms.',
    category: 'distribution',
    engine: 'svg',
    dataShape: 'distribution',
    icon: '📐',
  },
  {
    id: 'gantt',
    name: 'Gantt chart',
    description: 'Horizontal timeline of tasks. Project schedules, sprints.',
    category: 'other',
    engine: 'svg',
    dataShape: 'gantt',
    icon: '📅',
  },
  {
    id: 'timeline',
    name: 'Timeline',
    description: 'Chronological events on a line. History, milestones, releases.',
    category: 'other',
    engine: 'svg',
    dataShape: 'timeline-events',
    icon: '⏳',
  },
  {
    id: 'error-bars',
    name: 'Error bars',
    description: 'Values with uncertainty ranges. Scientific data, confidence intervals.',
    category: 'distribution',
    engine: 'svg',
    dataShape: 'error',
    icon: '📊',
  },

  // ── Maps ──────────────────────────────────────────
  {
    id: 'choropleth-map',
    name: 'Choropleth map',
    description: 'Countries coloured by value. GDP, population, indices.',
    category: 'map',
    engine: 'svg',
    dataShape: 'geo',
    icon: '🗺',
  },
  {
    id: 'bubble-map',
    name: 'Bubble map',
    description: 'Sized circles on country centroids. City populations, emissions.',
    category: 'map',
    engine: 'svg',
    dataShape: 'geo',
    icon: '🫧',
  },
  {
    id: 'dot-map',
    name: 'Dot map',
    description: 'Small dots at locations. Event density, infrastructure.',
    category: 'map',
    engine: 'svg',
    dataShape: 'geo',
    icon: '📍',
  },
  {
    id: 'connection-map',
    name: 'Connection map',
    description: 'Arcs between countries. Trade routes, flight paths.',
    category: 'map',
    engine: 'svg',
    dataShape: 'flow',
    icon: '✈',
  },
  {
    id: 'flow-map',
    name: 'Flow map',
    description: 'Directional arrows between locations. Migration, supply chains.',
    category: 'map',
    engine: 'svg',
    dataShape: 'flow',
    icon: '➡',
  },
];

export const CHART_CATEGORIES: { id: string; label: string }[] = [
  { id: 'line', label: 'Line — change over time' },
  { id: 'bar', label: 'Bar — amounts & categories' },
  { id: 'horizontal', label: 'Horizontal — rankings' },
  { id: 'scatter', label: 'Scatter — relationships' },
  { id: 'part-to-whole', label: 'Part-to-whole' },
  { id: 'distribution', label: 'Distribution' },
  { id: 'ranking', label: 'Ranking' },
  { id: 'flow', label: 'Flow & hierarchy' },
  { id: 'map', label: 'Maps — geographic' },
  { id: 'other', label: 'Specialised' },
];
